### ISSUE TITLE
Generate CSV Files

### ISSUE THREAD

**Issue by sreeder** [UCHIC/h2outility#2]
Generate CSV files with the time series values. 

- [x] CSV files should be divided for each Site, QC Level, and Source.
- [x] Users should be able to choose whether to group multiple series into a single file, or to generate a single file per time series.
- [x] File headers should provide information about the series they contain

**Comment by fryarludwig** [comment]
File headers will need a little more work before they're ready, but it's close.

**Comment by fryarludwig** [comment]
File headers now contain information about their site, QC level, and source. We may want to allow users to add a custom header portion in the future.
