### ISSUE TITLE
User interface design

### ISSUE THREAD

**Issue by sreeder** [UCHIC/h2outility#4]
Implement and test a user interface that allows the user to easily understand and use the H2O utility, similar to the example below.

![image](https://user-images.githubusercontent.com/8953221/27887378-b53badec-619d-11e7-9150-fd6a8c4ee71d.png)

**Comment by fryarludwig** [comment]
GUI components are completed - there may be small tweaks or behavior updates that need to happen, but no known issues. 

Current layout below:
![image](https://user-images.githubusercontent.com/8953221/28493353-a1f26f68-6ed2-11e7-8c8d-31d4683c767c.png)

**Comment by fryarludwig** [comment]
This is ready for testing
